name: salary_percentage
description: "Multiple percentage helpers"

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  meta: ^1.11.0

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
